apiVersion: v1
kind: Service
metadata:
  name: netsentry
  labels:
    app.kubernetes.io/name: netsentry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: netsentry
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netsentry
  labels:
    app.kubernetes.io/name: netsentry
automountServiceAccountToken: false
