"""What a regulator asks for, and what this repository can actually show them.

A network intrusion detector that decides which traffic a human looks at is, under the EU AI
Act's taxonomy, the kind of system that attracts obligations: it is used for security, it makes
automated determinations that affect what gets investigated, and its errors are asymmetric in a
way somebody has to be accountable for. Whether *this* system is formally high-risk is a legal
question this file does not answer. What it does answer is the engineering question underneath
it — **for each obligation a regulator or an internal model-risk function would name, is there
an artifact in this repository that satisfies it, and where is it?**

Two frameworks are mapped, because they ask different questions:

- **NIST AI RMF 1.0** (the four functions GOVERN, MAP, MEASURE, MANAGE) is process-shaped: it
  asks whether an organisation *knows* what it built and *watches* what it does. It is
  voluntary, widely adopted, and the closest thing to a shared vocabulary for "we take this
  seriously".
- **The EU AI Act's high-risk articles** (9 risk management, 10 data governance, 11-12
  documentation and logging, 13 transparency, 14 human oversight, 15 accuracy, robustness and
  cybersecurity) are obligation-shaped: they ask whether specific things *exist*.

The mapping follows the same rule as the [ATLAS threat model](atlas.md), and it is the rule
that separates this from every compliance spreadsheet: **every claim names a file, and the file
is checked to exist.** A study that gets deleted or renamed downgrades its own obligation to
`unmet` on the next run rather than silently continuing to satisfy a regulator on paper. The
gaps are in the same table as the coverage, because a conformance document listing only what
you did is marketing with a legal font.

The output is a report plus a machine-readable JSON mapping, so an auditor can consume the
claims without reading Python — and so a reviewer can diff two runs and see what moved.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from netsentry.log import get_logger

if TYPE_CHECKING:
    from netsentry.config import Settings

logger = get_logger(__name__)

REPORT_NAME = "compliance.md"
MAPPING_NAME = "compliance_mapping.json"

#: Framework versions this mapping was written against. A control mapped without a version is
#: a control mapped against whatever the author remembered.
NIST_VERSION = "NIST AI RMF 1.0 (January 2023)"
EU_VERSION = "Regulation (EU) 2024/1689, high-risk obligations (Articles 9-15)"

MET = "met"
PARTIAL = "partial"
UNMET = "unmet"
NOT_APPLICABLE = "not applicable"

_GRADE_ORDER = (MET, PARTIAL, UNMET, NOT_APPLICABLE)


@dataclass(frozen=True)
class Control:
    """One obligation, what satisfies it here, and where the evidence lives."""

    framework: str
    reference: str
    title: str
    grade: str
    evidence: str
    module: str = ""
    report: str = ""
    command: str = ""


# The mapping. Controls with no evidence paths are gaps and are listed deliberately.
CONTROLS: tuple[Control, ...] = (
    # ---------------------------------------------------------------- NIST AI RMF: GOVERN
    Control(
        framework="NIST AI RMF",
        reference="GOVERN 1.2",
        title="Risk management processes are documented and traceable",
        grade=MET,
        evidence=(
            "Every claim in this repository is produced by a command, written to a report, and "
            "regenerated by `netsentry analyze`; the release gate encodes the definition of "
            "done as an executable check rather than a checklist."
        ),
        module="netsentry/evaluation/gate.py",
        report="docs/reports/gate.md",
        command="netsentry gate",
    ),
    Control(
        framework="NIST AI RMF",
        reference="GOVERN 1.5",
        title="Ongoing monitoring and periodic review are planned",
        grade=MET,
        evidence=(
            "Drift monitoring (PSI, KS+BH, kernel two-sample), SLO burn-rate alerting whose "
            "Prometheus rules are generated from the measured operating point, and a priced "
            "retrain policy comparing never / periodic / drift-triggered."
        ),
        module="netsentry/monitoring/retrain_policy.py",
        report="docs/reports/retrain_policy.md",
        command="netsentry retrainpolicy",
    ),
    Control(
        framework="NIST AI RMF",
        reference="GOVERN 4.1",
        title="A culture of risk identification is fostered; negative results are recorded",
        grade=MET,
        evidence=(
            "NOTES.md is a running self-audit of failures, wrong predictions and bugs found "
            "before release; several studies are kept specifically because their result was "
            "negative (cascade, defer, discovery, strategic, acquisition)."
        ),
        report="NOTES.md",
    ),
    Control(
        framework="NIST AI RMF",
        reference="GOVERN 6.1",
        title="Third-party software and data risks are managed",
        grade=MET,
        evidence=(
            "A CycloneDX SBOM with Package URLs, a signed model-integrity manifest, and a "
            "`verify` gate that exits non-zero when the artifact's bytes change."
        ),
        module="netsentry/governance/provenance.py",
        report="docs/reports/provenance.md",
        command="netsentry verify",
    ),
    # ------------------------------------------------------------------- NIST AI RMF: MAP
    Control(
        framework="NIST AI RMF",
        reference="MAP 1.1",
        title="Intended purpose, context and limits are understood and documented",
        grade=MET,
        evidence=(
            "The model card states the intended use, the operating point, and the limits; the "
            "architecture document has an explicit out-of-scope section."
        ),
        module="netsentry/evaluation/model_card.py",
        report="docs/MODEL_CARD.md",
        command="netsentry modelcard",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MAP 2.3",
        title="Scientific integrity and TEVV considerations are documented",
        grade=MET,
        evidence=(
            "The headline evaluation is a temporal split with the optimistic stratified number "
            "reported beside it, and the leakage study reproduces the field's ~99% result to "
            "price each source of it."
        ),
        module="netsentry/evaluation/leakage.py",
        report="docs/reports/leakage.md",
        command="netsentry leakage",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MAP 5.1",
        title="Likelihood and magnitude of each impact are understood",
        grade=MET,
        evidence=(
            "Cost-sensitive thresholds put a currency on false positives and negatives; the "
            "base-rate study shows what alert precision does at production prevalence; the "
            "queue simulation puts the analyst in the loop."
        ),
        module="netsentry/evaluation/cost.py",
        report="docs/reports/cost.md",
        command="netsentry cost",
    ),
    # --------------------------------------------------------------- NIST AI RMF: MEASURE
    Control(
        framework="NIST AI RMF",
        reference="MEASURE 2.3",
        title="System performance is demonstrated in deployment-like conditions",
        grade=MET,
        evidence=(
            "Detection is reported at fixed false-positive budgets on a temporal split whose "
            "test days share no attack class with training, plus a cross-dataset transfer study "
            "and a per-service parity audit."
        ),
        module="netsentry/evaluation/report.py",
        report="docs/reports/evaluation.md",
        command="netsentry eval",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MEASURE 2.5",
        title="Validity and reliability are demonstrated, including uncertainty",
        grade=MET,
        evidence=(
            "Bootstrap confidence intervals, a cross-seed noise floor, conformal prediction "
            "sets, epistemic/aleatoric decomposition, and distribution-free risk control with "
            "its expectation-versus-tail distinction measured."
        ),
        module="netsentry/evaluation/risk_control.py",
        report="docs/reports/risk_control.md",
        command="netsentry riskcontrol",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MEASURE 2.7",
        title="Security and resilience are evaluated",
        grade=MET,
        evidence=(
            "Evasion, poisoning, backdoor, membership-inference, extraction and watermarking "
            "studies, governed as one threat model against MITRE ATLAS with the residual gaps "
            "named rather than omitted."
        ),
        module="netsentry/intel/atlas.py",
        report="docs/reports/atlas.md",
        command="netsentry atlas",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MEASURE 2.11",
        title="Fairness and bias across relevant groups are evaluated",
        grade=PARTIAL,
        evidence=(
            "Per-service detection parity is audited with Wilson intervals and served as a "
            "`per_service` threshold profile, and automatic slice discovery searches for "
            "underperforming regions nobody predefined. Both are *operational* groupings; this "
            "system processes no personal attributes, so demographic fairness is not assessed "
            "and no claim about it should be inferred."
        ),
        module="netsentry/evaluation/subgroups.py",
        report="docs/reports/subgroups.md",
        command="netsentry subgroups",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MEASURE 2.13",
        title="Effectiveness of the measurement approach itself is assessed",
        grade=MET,
        evidence=(
            "Metamorphic testing provides a label-free correctness oracle, validated by a "
            "three-oracle mutation study in which none of labelled accuracy, invariants or the "
            "canary dominates the others."
        ),
        module="netsentry/robustness/metamorphic.py",
        report="docs/reports/metamorphic.md",
        command="netsentry metamorphic",
    ),
    # ---------------------------------------------------------------- NIST AI RMF: MANAGE
    Control(
        framework="NIST AI RMF",
        reference="MANAGE 2.2",
        title="Mechanisms are in place to sustain the value of deployed systems",
        grade=MET,
        evidence=(
            "Champion/challenger promotion with paired-bootstrap margins from the measured "
            "noise floor, shadow scoring on live traffic, canary-gated hot reload, and "
            "threshold refresh priced against retraining."
        ),
        module="netsentry/models/promotion.py",
        report="docs/reports/promotion.md",
        command="netsentry promote",
    ),
    Control(
        framework="NIST AI RMF",
        reference="MANAGE 4.1",
        title="Post-deployment monitoring plans are implemented, including incident response",
        grade=PARTIAL,
        evidence=(
            "Drift monitors, SLO burn-rate alerts and incident reports exist and are wired to "
            "Prometheus; what does not exist is an organisational response *plan* — who is "
            "paged, what authority they have, and how a rollback is authorised are outside "
            "what a repository can evidence."
        ),
        module="netsentry/monitoring/slo.py",
        report="docs/reports/slo.md",
        command="netsentry slo",
    ),
    # ------------------------------------------------------------------- EU AI Act
    Control(
        framework="EU AI Act",
        reference="Article 9",
        title="Risk management system across the lifecycle",
        grade=PARTIAL,
        evidence=(
            "Risks are identified, measured and re-measured after mitigation throughout "
            "(measure - fix - re-measure appears in hardening, poisoning defence and the "
            "control-loop attack). What is missing is the formal artifact: a maintained risk "
            "register with owners and residual-risk acceptance, which is a governance document "
            "rather than a study."
        ),
        module="netsentry/robustness/hardening.py",
        report="docs/reports/hardening.md",
        command="netsentry harden",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 10",
        title="Data governance: relevance, representativeness, errors and gaps examined",
        grade=MET,
        evidence=(
            "The data card documents provenance, known defects and the label consolidation; "
            "validation gates enforce schema, label and duplicate checks; the label audit uses "
            "confident learning and self-validates on planted flips."
        ),
        module="netsentry/data/validation.py",
        report="docs/DATA_CARD.md",
        command="netsentry validate",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 11",
        title="Technical documentation sufficient to assess conformity",
        grade=MET,
        evidence=(
            "An auto-generated model card, an architecture document, a data card, and "
            "reports produced by the same commands that produced the numbers in them."
        ),
        module="netsentry/evaluation/model_card.py",
        report="docs/reports/model_card_generated.md",
        command="netsentry modelcard",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 12",
        title="Automatic recording of events (logging) over the system's lifetime",
        grade=MET,
        evidence=(
            "A hash-chained, tamper-evident alert ledger with a published anchor closing the "
            "tail-truncation gap and O(log n) Merkle inclusion proofs, so an alert history can "
            "be attested without being disclosed. Six tamper attacks are executed against it."
        ),
        module="netsentry/governance/ledger.py",
        report="docs/reports/ledger.md",
        command="netsentry ledger verify",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 13",
        title="Transparency: operation interpretable enough for the deployer to use output",
        grade=MET,
        evidence=(
            "Every prediction carries SHAP attributions, a MITRE technique, a conformal "
            "prediction set and a recommended action; anomaly flags carry their own "
            "attribution; nearest known training flows are available as evidence."
        ),
        module="netsentry/explain/shap_explainer.py",
        report="docs/reports/anchors.md",
        command="netsentry anchors",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 14",
        title="Human oversight: designed so a person can intervene and override",
        grade=PARTIAL,
        evidence=(
            "The system routes rather than acts: conformal sets produce auto-alert / auto-clear "
            "/ review actions, learning-to-defer prices escalation against analyst capacity, "
            "and alert-queue planning sizes the human budget. It does not implement an "
            "override *interface* or record who overrode what, which is a product surface this "
            "repository does not have."
        ),
        module="netsentry/evaluation/defer.py",
        report="docs/reports/defer.md",
        command="netsentry defer",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 15 (accuracy)",
        title="Appropriate accuracy, declared with its metrics",
        grade=MET,
        evidence=(
            "Accuracy is banned from the headline; detection is declared at fixed "
            "false-positive budgets with certified budgets from an order statistic and the "
            "sample-size floor below which no threshold can certify one."
        ),
        module="netsentry/evaluation/neyman_pearson.py",
        report="docs/reports/neyman_pearson.md",
        command="netsentry npclass",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 15 (robustness)",
        title="Resilience to errors, faults and inconsistencies",
        grade=MET,
        evidence=(
            "A sensor-failure audit runs the deployed model against a broken exporter; "
            "monotone constraints make an entire evasion family impossible by construction; "
            "interval-arithmetic verification gives a sound absolute robustness radius."
        ),
        module="netsentry/robustness/verify_trees.py",
        report="docs/reports/verify_trees.md",
        command="netsentry verifytrees",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 15 (cybersecurity)",
        title="Resilience to attempts to alter use, outputs or performance",
        grade=MET,
        evidence=(
            "Data poisoning and backdoor attacks with defences re-measured, model extraction "
            "and its transfer evasion, membership inference with a differential-privacy "
            "answer priced, and byte-level artifact attestation at load and at deploy."
        ),
        module="netsentry/robustness/backdoor.py",
        report="docs/reports/backdoor.md",
        command="netsentry backdoor",
    ),
    Control(
        framework="EU AI Act",
        reference="Article 17",
        title="Quality management system",
        grade=UNMET,
        evidence=(
            "No quality management system exists here, and one cannot: Article 17 is about an "
            "organisation's documented procedures, responsibilities and change control, not "
            "about code. The CI pipeline and release gate are inputs to such a system, not a "
            "substitute for it."
        ),
    ),
    Control(
        framework="EU AI Act",
        reference="Article 27",
        title="Fundamental rights impact assessment",
        grade=NOT_APPLICABLE,
        evidence=(
            "Required of deployers in specific public-body and essential-service contexts. "
            "This repository is a reference implementation with no deployer and no affected "
            "persons; the assessment belongs to whoever deploys it, and the data card's "
            "statement that flow records identify people is the input they would start from."
        ),
    ),
    Control(
        framework="EU AI Act",
        reference="Article 43",
        title="Conformity assessment procedure",
        grade=UNMET,
        evidence=(
            "No conformity assessment has been performed. Listing this as a gap is the point: "
            "a repository can produce the technical evidence an assessment consumes and cannot "
            "perform the assessment on itself."
        ),
    ),
)


@dataclass
class VerifiedControl:
    """A control after checking that the artifact it names is really there."""

    control: Control
    module_exists: bool
    report_exists: bool

    @property
    def verified(self) -> bool:
        """A claim counts only if the evidence it names exists on disk."""
        if not self.control.module and not self.control.report:
            return self.control.grade in {UNMET, NOT_APPLICABLE}
        return self.module_exists and self.report_exists

    @property
    def effective_grade(self) -> str:
        """The grade after verification — an unbacked claim is not compliance."""
        return self.control.grade if self.verified else UNMET


def verify_controls(
    repo_root: Path, controls: tuple[Control, ...] = CONTROLS
) -> list[VerifiedControl]:
    """Check every control's evidence against the files on disk.

    This is the whole mechanism. A conformance mapping that cannot fail is a decorative one,
    and the usual failure of compliance documents is not dishonesty — it is that the evidence
    moved and the document did not.
    """
    return [
        VerifiedControl(
            control=control,
            module_exists=not control.module or (repo_root / control.module).exists(),
            report_exists=not control.report or (repo_root / control.report).exists(),
        )
        for control in controls
    ]


def grade_counts(verified: list[VerifiedControl], framework: str | None = None) -> dict[str, int]:
    """How many controls sit at each grade after verification."""
    counts = dict.fromkeys(_GRADE_ORDER, 0)
    for item in verified:
        if framework and item.control.framework != framework:
            continue
        counts[item.effective_grade] = counts.get(item.effective_grade, 0) + 1
    return counts


def coverage_ratio(verified: list[VerifiedControl], framework: str | None = None) -> float:
    """Share of *applicable* controls that are met, with partials counted as half.

    Not-applicable controls leave the denominator rather than counting as wins: a system with
    no deployer does not get credit for a deployer's obligation.
    """
    applicable = [
        item
        for item in verified
        if item.effective_grade != NOT_APPLICABLE
        and (framework is None or item.control.framework == framework)
    ]
    if not applicable:
        return 0.0
    score = sum(
        1.0 if item.effective_grade == MET else 0.5 if item.effective_grade == PARTIAL else 0.0
        for item in applicable
    )
    return score / len(applicable)


def build_mapping(verified: list[VerifiedControl]) -> dict[str, object]:
    """The machine-readable artifact an auditor can consume without reading Python."""
    return {
        "frameworks": {"nist": NIST_VERSION, "eu": EU_VERSION},
        "generated_by": "netsentry compliance",
        "verification": "each control's module and report are checked to exist in the repository",
        "controls": [
            {
                "framework": item.control.framework,
                "reference": item.control.reference,
                "title": item.control.title,
                "claimed_grade": item.control.grade,
                "effective_grade": item.effective_grade,
                "verified": item.verified,
                "evidence": item.control.evidence,
                "module": item.control.module,
                "report": item.control.report,
                "command": item.control.command,
            }
            for item in verified
        ],
    }


def run_compliance_report(settings: Settings) -> Path:
    """Verify every control and write the conformance report + JSON mapping."""
    repo_root = Path(settings.paths.reports_dir).resolve().parent.parent
    verified = verify_controls(repo_root)
    mapping_path = settings.paths.reports_dir / MAPPING_NAME
    mapping_path.parent.mkdir(parents=True, exist_ok=True)
    mapping_path.write_text(json.dumps(build_mapping(verified), indent=2), encoding="utf-8")

    out_path = settings.paths.reports_dir / REPORT_NAME
    out_path.write_text(_render(verified), encoding="utf-8")
    logger.info(
        "Wrote compliance report",
        extra={
            "path": str(out_path),
            "nist": round(coverage_ratio(verified, "NIST AI RMF"), 3),
            "eu": round(coverage_ratio(verified, "EU AI Act"), 3),
        },
    )
    return out_path


def _control_table(verified: list[VerifiedControl], framework: str) -> str:
    rows = ["| reference | obligation | status | evidence |", "|---|---|---|---|"]
    for item in verified:
        if item.control.framework != framework:
            continue
        grade = item.effective_grade
        marker = {MET: "met", PARTIAL: "**partial**", UNMET: "**unmet**"}.get(
            grade, "not applicable"
        )
        if not item.verified and item.control.grade != grade:
            marker += " (evidence missing)"
        link = (
            f"[{item.control.report}](../../{item.control.report})" if item.control.report else "—"
        )
        command = f"`{item.control.command}`" if item.control.command else ""
        rows.append(
            f"| {item.control.reference} | {item.control.title} | {marker} | "
            f"{item.control.evidence} {link} {command} |"
        )
    return "\n".join(rows)


def _summary_read(verified: list[VerifiedControl]) -> str:
    nist = coverage_ratio(verified, "NIST AI RMF")
    eu = coverage_ratio(verified, "EU AI Act")
    counts = grade_counts(verified)
    unverified = [item for item in verified if not item.verified and item.control.grade != UNMET]
    return (
        f"Across {len(verified)} controls: **{counts[MET]} met**, {counts[PARTIAL]} partial, "
        f"{counts[UNMET]} unmet, {counts[NOT_APPLICABLE]} not applicable — "
        f"{nist:.0%} of the applicable NIST functions and {eu:.0%} of the applicable EU "
        "articles, counting a partial as a half.\n\n"
        + (
            f"**{len(unverified)} control(s) claim evidence that is not present** and have been "
            "downgraded automatically. That is the mechanism working: the file moved and the "
            "document noticed."
            if unverified
            else "Every claim's evidence was found on disk. That sentence is worth exactly as "
            "much as the check behind it, which is why the check is in the code rather than in "
            "the prose."
        )
    )


def _gap_read(verified: list[VerifiedControl]) -> str:
    gaps = [item for item in verified if item.effective_grade in {UNMET, PARTIAL}]
    if not gaps:
        return "No gaps, which would be a suspicious thing for a compliance document to say."
    lines = "\n".join(
        f"- **{item.control.reference} — {item.control.title}** ({item.effective_grade}): "
        f"{item.control.evidence}"
        for item in gaps
    )
    return (
        "The gaps are the useful half of this document, and they share a shape: **the things "
        "this repository cannot evidence are organisational rather than technical.**\n\n"
        f"{lines}\n\n"
        "A quality management system, a risk register with named owners, an override interface "
        "that records who overrode what, and a conformity assessment are all things a *company* "
        "has, not things a codebase has. Any conformance claim that marked them green from a "
        "repository scan would be describing software as though it were an organisation — which "
        "is the specific failure mode this document is built to avoid."
    )


def _render(verified: list[VerifiedControl]) -> str:
    return f"""# NetSentry — Conformance Mapping (NIST AI RMF and the EU AI Act)

_{NIST_VERSION}; {EU_VERSION}. Every control names an artifact and every artifact is checked to
exist: a study that is deleted or renamed downgrades its own control on the next run. Regenerate
with `netsentry compliance`; the machine-readable mapping is
[`{MAPPING_NAME}`]({MAPPING_NAME})._

## Why this report exists

A detector that decides which traffic a human looks at attracts obligations, and the engineering
question underneath the legal one is answerable: **for each thing a regulator or an internal
model-risk function would ask for, is there an artifact here that satisfies it, and where?**
This maps two frameworks that ask differently — NIST's AI RMF is process-shaped ("do you know
what you built and do you watch it?"), the EU AI Act's high-risk articles are obligation-shaped
("does this specific thing exist?").

{_summary_read(verified)}

## NIST AI RMF 1.0

{_control_table(verified, "NIST AI RMF")}

## EU AI Act — high-risk obligations

{_control_table(verified, "EU AI Act")}

## The gaps

{_gap_read(verified)}

## Scope and honest limits

- **This is not a legal assessment and nothing here is legal advice.** Whether this system is
  high-risk under the Act, and which obligations attach to a developer as against a deployer,
  are questions for counsel. The mapping is an engineering inventory written in a regulator's
  vocabulary so that the conversation can start from artifacts rather than from adjectives.
- **The frameworks are pinned and will move.** Both are cited with their versions because a
  control mapped without a version is a control mapped against whatever the author remembered;
  the Act's harmonised standards in particular are still being written.
- **Verification checks existence, not adequacy.** The mechanism proves a named report is
  present, not that it is any good — that judgement is what the reports themselves are for, and
  a reviewer who trusts this table without opening one has learned nothing.
- **A repository cannot be compliant.** An organisation can. Everything marked unmet is
  organisational by nature, and the honest reading of a strong technical column is that the
  *evidence* an assessment would consume exists — not that the assessment has been passed."""
